### ISSUE TITLE
Insatll kubefm by cmd

### ISSUE THREAD

**Issue by AngelaWanChina** [flowerinthenight/kubepfm#4]
Hello guys:
I wanner to know how to install the kubefm on windows by cmd? looking forward for your reply

**Comment by flowerinthenight** [comment]
Sorry, I missed this.

I think for Windows, you have 2 options.
1) If you're using the later versions of Win10, you can use WSL and install brew indicated in the README.
2) If you don't want that, you can just do a `go get`, in which case, you need to have Go installed in your Windows system.
