### ISSUE TITLE
Exposing multiple ports on the same service

### ISSUE THREAD

**Issue by jasonnance** [flowerinthenight/kubepfm#5]
Hi, thanks for this very useful tool.  I'm attempting to use it to expose the Pachyderm dashboard, which exposes two ports under the same service -- i.e., the following specification for kubepfm:

    ns=pachyderm:service/dash:30080:8080
    ns=pachyderm:service/dash:30081:8081

However, this doesn't work currently (only one of the ports is properly exposed), since kubepfm creates a unique key that doesn't include the ports, and one of the specifications overwrites the other.  Is allowing two ports to be exposed for the same service problematic for some reason?  If not, would you accept a PR that adds this functionality?

Thanks!

**Comment by flowerinthenight** [comment]
> Is allowing two ports to be exposed for the same service problematic for some reason? If not, would you accept a PR that adds this functionality?
Not at all, no. And a PR would be welcome. Just make sure that the current args are backwards compatible as this tool is quite integrated with our dev environment.

**Comment by flowerinthenight** [comment]
Merged and released. Thanks.
